const Projetos = [
  {
    img: "../src/assets/projects-img/Captura de tela 2025-01-12 174914.png",
    title: "Biblioteca de Jogos",
    projectLink: "",
    githubLink: "",
    html: "../src/assets/logos/HTML.png",
    css: "../src/assets/logos/css-3.svg",
    js: "../src/assets/logos/JavaScript-logo.png",
    scss: "../src/assets/logos/sass-1.svg",
    id: 14568,
  },
  {
    img: "../src/assets/projects-img/Captura de tela 2025-01-13 124340.png",
    title: "Adivinhação de Números",
    projectLink: "",
    githubLink: "",
    html: "../src/assets/logos/HTML.png",
    css: "../src/assets/logos/css-3.svg",
    js: "../src/assets/logos/JavaScript-logo.png",
    scss: "../src/assets/logos/sass-1.svg",
    id: 25685,
  },
  {
    img: "../src/assets/projects-img/Captura de tela 2025-01-24 201255.png",
    title: "Calculadora de Médias",
    projectLink: "",
    githubLink: "",
    html: "../src/assets/logos/HTML.png",
    css: "../src/assets/logos/css-3.svg",
    js: "../src/assets/logos/JavaScript-logo.png",
    scss: "../src/assets/logos/sass-1.svg",
    id: 3346456,
  },
  {
    img: "../src/assets/projects-img/image.png",
    title: "Cards de precificação",
    projectLink: "",
    githubLink: "",
    html: "../src/assets/logos/HTML.png",
    css: "../src/assets/logos/css-3.svg",
    js: "../src/assets/logos/JavaScript-logo.png",
    scss: "../src/assets/logos/sass-1.svg",
    id: 1234,
  },
];

export default Projetos;
